# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condottieri_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionevent',
            name='after',
            field=models.CharField(choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1),
        ),
        migrations.AlterField(
            model_name='conversionevent',
            name='before',
            field=models.CharField(choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1),
        ),
        migrations.AlterField(
            model_name='disbandevent',
            name='type',
            field=models.CharField(choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1),
        ),
        migrations.AlterField(
            model_name='expenseevent',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='movementevent',
            name='type',
            field=models.CharField(choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1),
        ),
        migrations.AlterField(
            model_name='newunitevent',
            name='type',
            field=models.CharField(choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='code',
            field=models.CharField(choices=[('H', 'Hold'), ('B', 'Besiege'), ('-', 'Advance'), ('=', 'Conversion'), ('C', 'Convoy'), ('S', 'Support')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='conversion',
            field=models.CharField(blank=True, choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='subcode',
            field=models.CharField(blank=True, choices=[('H', 'Hold'), ('B', 'Besiege'), ('-', 'Advance'), ('=', 'Conversion'), ('C', 'Convoy'), ('S', 'Support')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='subconversion',
            field=models.CharField(blank=True, choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='subtype',
            field=models.CharField(blank=True, choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1),
        ),
        migrations.AlterField(
            model_name='retreatevent',
            name='type',
            field=models.CharField(choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1),
        ),
        migrations.AlterField(
            model_name='unitevent',
            name='type',
            field=models.CharField(choices=[('A', 'Army'), ('F', 'Fleet'), ('G', 'Garrison')], max_length=1),
        ),
    ]
